version: '2.3'

services:
  nginx:
    restart: always
    build: ./nginx
    ports:
      - "8082:80"
    links:
      - sentiment
  sentiment:
    restart: always
    runtime: nvidia
    volumes:
      - $HOME/.models/:/models
      - $HOME/.pytorch_pretrained_bert/:/root/.pytorch_pretrained_bert
    build: ./sentiment
